#
# plugin settings
#
name: KuroDiscord
version: ${project.version}
main: host.kuro.kurodiscord.KuroDiscord
api-version: 1.15
authors: [kuro-123]
description: Discord plugin for 123 server culture spigot
website: http://kuro.host/wordpress/
